### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ForBai** [liulihaocai/Fluidity#7]
Crash log
```
[15:46:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:46:16] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:46:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:46:16] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[15:46:16] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_275, running on Linux:amd64:5.15.0-58-generic, installed at /home/lars/.sdkman/candidates/java/8.0.275.open-adpt/jre
[15:46:16] [main/WARN] [FML]: The coremod me.liuli.fluidity.inject.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:46:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:46:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:46:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:46:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:46:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:46:17] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:46:17] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:46:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:46:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:46:17] [main/INFO] [STDOUT]: [me.liuli.fluidity.inject.HookUtilityCompatTransformer$Companion:initHooks:69]: HookUtility initialized with [26 hooks, 5 method processors, 45 access records] in 237.0 ms
[15:46:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:46:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:46:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:46:17] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:46:18] [Client thread/INFO]: Setting user: LaMinezz
[15:46:18] [Client thread/INFO] [Fluidity]: Initialize Fluidity git-9348ccf
[15:46:18] [Client thread/INFO]: LWJGL Version: 2.9.4
[15:46:18] [Client thread/INFO] [FML]: MinecraftForge v11.15.1.2318 Initialized
[15:46:19] [Client thread/INFO] [FML]: Replaced 229 ore recipies
[15:46:19] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[15:46:19] [Client thread/INFO] [FML]: Searching /home/lars/.local/share/multimc/instances/1.8.92/.minecraft/mods for mods
[15:46:20] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load
[15:46:20] [Client thread/INFO] [FML]: FML has found a non-mod file Fluidity-2.0.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[15:46:20] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[15:46:20] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[15:46:20] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[15:46:20] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[15:46:20] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[15:46:20] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[15:46:20] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[15:46:20] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[15:46:20] [Client thread/INFO] [FML]: Applying holder lookups
[15:46:20] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[15:46:20] [Client thread/INFO] [FML]: Holder lookups applied
[15:46:20] [Client thread/INFO] [FML]: Injecting itemstacks
[15:46:20] [Client thread/INFO] [FML]: Itemstack injection complete
[15:46:20] [Client thread/INFO] [STDOUT]: [tv.twitch.StandardCoreAPI:<init>:16]: If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[15:46:20] [Client thread/ERROR]: Couldn't initialize twitch stream
[15:46:20] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:46:20] [Thread-8/INFO]: Initializing LWJGL OpenAL
[15:46:20] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:46:20] [Thread-8/INFO]: OpenAL initialized.
[15:46:21] [Client thread/INFO] [FML]: Max texture size: 16384
[15:46:21] [Client thread/INFO]: Created: 16x16 textures-atlas
[15:46:21] [Sound Library Loader/INFO]: Sound engine started
[15:46:21] [Client thread/INFO] [FML]: Injecting itemstacks
[15:46:21] [Client thread/INFO] [FML]: Itemstack injection complete
[15:46:21] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 3 mods
[15:46:21] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[15:46:21] [Client thread/INFO]: SoundSystem shutting down...
[15:46:21] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[15:46:21] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:46:21] [Thread-10/INFO]: Initializing LWJGL OpenAL
[15:46:21] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:46:21] [Thread-10/INFO]: OpenAL initialized.
[15:46:22] [Client thread/INFO] [FML]: Max texture size: 16384
[15:46:22] [Client thread/INFO]: Created: 512x512 textures-atlas
[15:46:22] [Sound Library Loader/INFO]: Sound engine started
[15:46:22] [Client thread/INFO] [Fluidity]: Loading Fluidity git-9348ccf
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: java.lang.reflect.InvocationTargetException
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2.invoke(HookProvider.kt:59)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2.invoke(HookProvider.kt:59)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at me.yuugiri.hutil.processor.hook.MethodHookProcessor.hookCallback(MethodHookProcessor.kt:42)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:46:22] [Client thread/INFO] [STDERR]: [me.liuli.fluidity.inject.hooks.HookProvider$genFunctionCallback$2:invoke:59]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:46:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
[15:46:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at me.liuli.fluidity.config.ConfigManager.<clinit>(ConfigManager.kt:147)
[15:46:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at me.liuli.fluidity.Fluidity.load(Fluidity.kt:44)
[15:46:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at me.liuli.fluidity.inject.hooks.impl.client.HookMinecraft.startGame(HookMinecraft.kt:35)
[15:46:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 24 more
```

**Comment by hax0r31337** [comment]
try re-install your minecraft?

**Comment by ForBai** [comment]
yes i tried and it didn't help same error
